name: Build and deploy docs

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install 'mkdocs-material>=7,<8'
      - uses: fregante/setup-git-user@v1 # committer info
      - run: mkdocs gh-deploy -b gh-pages-generated --force